#!/bin/sh

# NO APPARMOR
apt remove apparmor -y --purge

# add docker repository
apt update
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
apt-key fingerprint 0EBFCD88
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# install docker
apt update
apt-get install docker-ce docker-ce-cli containerd.io -y
usermod -aG docker vagrant
systemctl enable docker && systemctl start docker

# install minikube
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
install minikube-linux-amd64 /usr/local/bin/minikube
eval $(minikube docker-env)
runuser -l vagrant -c 'minikube start'
echo "alias kubectl='minikube kubectl'" >> /home/vagrant/.bashrc

# set up the minikube mount process as a service because it's annoying to have
# to run it manually all the time
cp /vagrant/minikube-mount.service /etc/systemd/system
systemctl enable minikube-mount
systemctl start minikube-mount
